const crystals = [
		{
			name: "Amethyst",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603199254/Amethyst_tir0fc.jpg",
			description: "Oh look, it's purple!",
			energy: "Amplifies",
			chakra: "Third eye | Crown",
			helps: "Intuition and insight | insomnia | Safe travel | Connecting to higher self & Divine | Creativity | Manifestation | Stress & anxiety | Nightmares | Addiction",
			placement: "Place on third eye chakra | above crown of head | near your bed | under pillow",
			bkgColor: " to bottom right, hsla(295, 82%, 19%, 1), hsla(342, 82%, 63%, 1)",
			visible: false,
		},
		{
			name: "Black Tourmaline",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603593580/black-tourmaline_ok2upr.jpg",
			description: "Oh look, it's black!",
			energy: "Absorbs",
			chakra: "Root",
			helps: "Psychic Protection | Protect Against Negativity | Grounding | Stress Release | Cleansing Negative Emotions",
			placement: "Pants pocket | Near root chakra | Next to bed | Between you & source of negativity",
			bkgColor: " to bottom right, hsla(360, 82%, 12%, 1), hsla(200, 87%, 22%, 1)",
			visible: false,
		},
        {
			name: "Kyanite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603646925/Kyanite_o5nzp0.jpg",
			description: "Oh look, it's black!",
			energy: "Dosen't hold energy",
			chakra: "Green - Heart | Blue - Throat",
			helps: "Creating Pathways from One Thing to Another | Clearing Blockage | Loyalty & Fairness | Memory Recall",
			placement: "On corresponding chakras | In your hand",
			bkgColor: " to bottom right, hsla(242, 82%, 27%, 1), hsla(242, 82%, 35%, 1)",
			visible: false,
		},
        {
			name: "Labradorite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603655431/Crystals/Labradorite_wbnb5c.jpg",
			energy: "Amplifies",
			chakra: "Throat | Third Eye",
			helps: "Amplify Magical Qualites | Reducing Negativity | Detoxification of Addictive Substances | Tempering Impulsivity | Aiding Inuition",
			placement: "On throat chakra | As a necklace | Near area of meditation",
			bkgColor: " to bottom right, hsla(126, 82%, 23%, 1), hsla(160, 82%, 26%, 1) ",
			visible: false,
		},
		{
			name: "Rose Quartz",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603199255/rose-quartz_i9biui.jpg",
			description: "It's so pretty!",
			energy: "Amplifies",
			chakra: "Heart",
			helps: "Compassion | Kindness | Unconditional Love | Self-Love | Emotional Healing | Joy | Peace | Playfulness",
			placement: " On a necklace | Bracelet | Ring (commitment finger) | Heart chakra",
			bkgColor: " to bottom right, hsla(360, 96%, 46%, 1), hsla(312, 96%, 67%, 1)",
			visible: false,
		},
        {
			name: "Selenite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603656125/Crystals/Selenite_nwvb4q.jpg",
			energy: "Amplifies",
			chakra: "Third Eye | Crown",
			helps: "Protecting Against Negativity | Cleansing Negative Energy | Cleansing Other Crystals & Aura | Connect with Intuition",
			placement: "On or near the third eye or crown chakra",
			bkgColor: " to bottom right, hsla(307, 82%, 24%, 1), hsla(280, 82%, 69%, 1) ",
			visible: false,
		}
	];

// TEMPLATE TO PLACE IN CRYSTALS VARIBLE
    // {
	// 		name: "",
	// 		image: "",
	// 		energy: "",
	// 		chakra: "",
	// 		helps: "",
	// 		placement: "",
	// 		bkgColor: " to bottom right, ",
	// 		visible: false,
	// 	}

    export default crystals;